"use client";

import React from "react";
import { InfoPageLayout } from "@/components/layout/InfoPageLayout";

export default function TermsPage() {
    return (
        <InfoPageLayout
            title="Terms of Excellence"
            subtitle="The fundamental protocols governing our partnership in pursuit of olfactory perfection."
        >
            <div className="space-y-12">
                <section>
                    <h2 className="text-2xl mb-6">Archival Acquisition</h2>
                    <p>
                        Acquiring a Lumina essence is more than a transaction; it is a custodial
                        responsibility. Each bottle is tracked via our digital warehouse and is
                        intended for personal evocative use.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl mb-6">Olfactory Intellectual Property</h2>
                    <p>
                        The unique synthesis results generated by our AI engine remain the
                        intellectual property of Lumina. You are granted an exclusive license
                        to replicate your signature scent as long as you remain a member
                        of the House.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl mb-6">Stabilization Period</h2>
                    <p>
                        All custom syntheses require a mandatory 90-day stabilization period
                        in our Grasse facility. By placing an order, you acknowledge and
                        accept this necessary duration to ensure molecular integrity.
                    </p>
                </section>
            </div>
        </InfoPageLayout>
    );
}
